### ISSUE TITLE
[Feature request]defaults to old values when `LoaderFunc` failed

### ISSUE THREAD

**Issue by qudongfang** [goburrow/cache#12]
# Feature request
Would you please consider adding a new option to support this?
`Get` defaults to old values when `LoaderFunc` returns an error in `LoadingCache`.

**Comment by qudongfang** [comment]
I found some information in [Guava Cache](https://github.com/google/guava) wiki about [`Refresh`](https://github.com/google/guava/wiki/CachesExplained#refresh) says that:
> If an exception is thrown while refreshing, the old value is kept, and the exception is logged and swallowed.

While it behaves differently in this project.
https://github.com/goburrow/cache/blob/576a8d1542c8e8c497af31460ff7acc669a6fa51/local.go#L149-L170

**Comment by nqv** [comment]
I believe this is fixed in https://github.com/goburrow/cache/commit/ed586e32006b30416a68137394a5f27d374c6eb0
