### ISSUE TITLE
Cache refresh to happen asynchronously

### ISSUE THREAD

**Issue by sanketpayghan** [goburrow/cache#13]
Currently if we set refreshAfterWrite time duration and key is accessed after that time refresh of cache happens in sync.

In case loader function is latent that particular call will be latent so need to have async refresh. Get will return old value and asynchronously refresh value to new.

**Comment by sanketpayghan** [comment]
Here is PR - https://github.com/goburrow/cache/pull/14 @davecheney @nqv

**Comment by cy490761462** [comment]
I think this feature is also required by our project. Is there any progress for this PR? @davecheney @nqv

**Comment by majintao** [comment]
no any process 。。。

**Comment by nqv** [comment]
I believe this is fixed in https://github.com/goburrow/cache/commit/ed586e32006b30416a68137394a5f27d374c6eb0
