### ISSUE TITLE
the load can not bring the oldValue to the func callback

### ISSUE THREAD

**Issue by yiting1122** [goburrow/cache#25]
![image](https://user-images.githubusercontent.com/4957538/125738971-502a41a7-d961-4f02-a398-7824dca12d8e.png)

i want to write an expire refresh strategy, but i need the old value

**Comment by nqv** [comment]
Right, it needs support for user-defined refresh function. I'll see if I can add it.

**Comment by nqv** [comment]
I have added [Reloader](https://github.com/goburrow/cache/blob/f6da914dd6e3546dffa8802919dbca80cd33abe3/cache.go#L61), would you please try `cache.WithReloader(...)` and let me know if it works for you.

```
go get github.com/goburrow/cache@f6da914dd6e3546dffa8802919dbca80cd33abe3
```
Note that you'll need to compute and call setter callback asynchronously, i.e in a go routine.
Thanks

**Comment by yiting1122** [comment]
ok， i will have a try, i have read the  source code。
And i have another question, may i use this cache in my product to provide service for some users, it's  stable? 
Thanks very much

**Comment by yiting1122** [comment]
it's works for me ,i have make a test. 
The important this is the above question,  it is stable fro product?

Thanks

**Comment by nqv** [comment]
I'm using this for my personal projects, but can't guarantee. See https://github.com/goburrow/cache/blob/master/LICENSE

**Comment by yiting1122** [comment]
ok, i will test fully.

if i have some questions, i will submit comments here.

Thanks
