### ISSUE TITLE
the refresh need return the err

### ISSUE THREAD

**Issue by yiting1122** [goburrow/cache#26]
![image](https://user-images.githubusercontent.com/4957538/126098224-66e5e76c-7d4d-4d46-802a-129a8aca63b5.png)

**Comment by nqv** [comment]
What do you need error returned for? I believe `Refresh` is mainly for reloading asynchronously so it shouldn't return error.

**Comment by yiting1122** [comment]
OK, if go c.load(k) ,it may cause error, but i do not know.

**Comment by nqv** [comment]
Do you mean calling c.load(k) in a go routine? I think the current behavior match [LoadingCache#refresh](https://guava.dev/releases/snapshot/api/docs/com/google/common/cache/LoadingCache.html#refresh(K))
