### ISSUE TITLE
Use  c.loader is ok ? why not c.reloader?

### ISSUE THREAD

**Issue by yiting1122** [goburrow/cache#27]
![image](https://user-images.githubusercontent.com/4957538/126322153-e45c893c-6623-480e-b534-7d2ae10e633c.png)

because this is a loading cache ,c.loader is can not be nil. 
Thanks

**Comment by yiting1122** [comment]
User may not set the reloader, i think use a flag is better way, when user set refreshAfterWrite the flag is true.
of course, if user not set the refreshAfterWrite i think must return nil

**Comment by nqv** [comment]
`loader` is different to `reloader`. The former is required for a LoadingCache but not in a normal Cache. The latter is optional and only for LoadingCache, along with `loader` when applications want their own reloading strategy.

**Comment by yiting1122** [comment]
if the reloader is not set , when the key expired, return the old value or return nil and delete the old value
i think it must return nil.

**Comment by nqv** [comment]
I believe a LoadingCache would never return nil (empty value). It should either return old value or blocking to get new value.

**Comment by nqv** [comment]
See also https://github.com/goburrow/cache/issues/13
