### ISSUE TITLE
Feature Request: Expire After Write

### ISSUE THREAD

**Issue by AdityaVivek** [goburrow/cache#6]
The cache seems to only have a feature to expire entries that are not accessed. What about expiring entries after a time limit? (Or is there is already a way to do this which I've missed?)

**Comment by nqv** [comment]
Yeah, it's not implemented. May be you can use `WithRefreshAfterWrite` with a `LoadingCache`

**Comment by AdityaVivek** [comment]
Thanks. I was using LoadingCache before this, but I wasn't sure what "refresh" meant in this context. I assume it means the entry will have its value cleared?

**Comment by nqv** [comment]
Hi, this is fixed in https://github.com/goburrow/cache/commit/4060fe738647abf6f1adbece2cd69c7fecb3e942
Would you please check out that version?
