### ISSUE TITLE
GetIfPresent not return cached value at once

### ISSUE THREAD

**Issue by qfrank** [goburrow/cache#7]
```
        c := cache.New(cache.WithMaximumSize(1))
	k := "hello"
	c.Put(k, "world")

	fmt.Println(c.GetIfPresent(k))

	time.Sleep(time.Second)

	fmt.Println(c.GetIfPresent("hello"))

        //output
        //<nil> false
        //world true
```
this output result don't like real google guava cache

**Comment by nqv** [comment]
Currently, It writes to cache asynchronously so you might not get it from cache immediately. Sorry for the inconvenience. I'll see if anything I can do to fix this.

**Comment by tony2001** [comment]
Yeah, you should really mention in the docs, this kind of behavior is definitely not what one would expect from a cache.

**Comment by nqv** [comment]
I believe this is fixed in https://github.com/goburrow/cache/commit/ed586e32006b30416a68137394a5f27d374c6eb0
